import Database from "better-sqlite3";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { log } from "@shared/logger";

/**
 * Per-session summary surfaced to the dashboard sidebar dropdown. claude-mem
 * (the user's installed memory plugin) maintains a `session_summaries` table
 * keyed by memory_session_id, with structured fields the dashboard renders
 * as a compact human-readable block.
 *
 * Lookup path (the schema requires a join):
 *   sdk_sessions.content_session_id = <claude session_id from /api/sessions>
 *   → sdk_sessions.memory_session_id (claude-mem's internal id)
 *   → session_summaries.memory_session_id
 *
 * The summary is regenerated by claude-mem's background worker after every
 * turn, so the newest row per (memory_session_id) is the freshest.
 */
export interface SessionSummary {
  request: string | null;
  investigated: string | null;
  learned: string | null;
  completed: string | null;
  nextSteps: string | null;
  createdAt: string;
}

// Cache the read-only DB handle for the process lifetime. claude-mem's worker
// holds the write lock; opening read-only here avoids contending with it.
let cachedDb: Database.Database | null = null;
let lastDbPath: string | null = null;

function dbPath(): string {
  return join(homedir(), ".claude-mem", "claude-mem.db");
}

function getDb(): Database.Database | null {
  const path = dbPath();
  if (!existsSync(path)) return null;
  if (cachedDb && lastDbPath === path) return cachedDb;
  try {
    cachedDb = new Database(path, { readonly: true, fileMustExist: true });
    lastDbPath = path;
    // WAL mode lets us read while claude-mem's worker writes; we don't need
    // to set it here because the worker already does, but enabling
    // `journal_mode` query-time would conflict on a readonly handle.
    return cachedDb;
  } catch (err) {
    log.warn("session-summary", "failed to open claude-mem db", { err: String(err) });
    return null;
  }
}

/**
 * Look up the most recent summary for a claude session id. Falls back to
 * null when:
 *   - claude-mem is not installed (db file missing)
 *   - the session has no entry yet (new session before claude-mem indexed it)
 *   - the session was a slash-command spawn that claude-mem didn't summarise
 *   - the db file is locked / corrupt
 *
 * Cheap: a single indexed JOIN with two integer-bounded comparisons. Safe
 * to call on every sidebar expand without polluting performance.
 */
export function getSessionSummary(sessionId: string): SessionSummary | null {
  const db = getDb();
  if (!db) return null;
  try {
    // Order by id DESC because session_summaries grows with each turn and
    // the latest row supersedes earlier ones. claude-mem doesn't currently
    // soft-delete older rows, so we explicitly take the newest.
    const row = db
      .prepare(
        `
        SELECT
          ss.request       AS request,
          ss.investigated  AS investigated,
          ss.learned       AS learned,
          ss.completed     AS completed,
          ss.next_steps    AS nextSteps,
          ss.created_at    AS createdAt
        FROM session_summaries ss
        JOIN sdk_sessions s ON s.memory_session_id = ss.memory_session_id
        WHERE s.content_session_id = ?
        ORDER BY ss.id DESC
        LIMIT 1
        `,
      )
      .get(sessionId) as
      | {
          request: string | null;
          investigated: string | null;
          learned: string | null;
          completed: string | null;
          nextSteps: string | null;
          createdAt: string;
        }
      | undefined;
    return row ?? null;
  } catch (err) {
    log.warn("session-summary", "query failed", { sessionId, err: String(err) });
    return null;
  }
}
